### PR TITLE
Feat/user management

### PR DESCRIPTION
**Pull request by successtar**
## Description

More End points and unit testing for the User Management

All endpoints available here https://documenter.getpostman.com/view/11412929/SzmjyaDv

Fixes #(14) #(19) #(21)

## How Has This Been Tested?
Manual and Auto
For auto test use `yarn test` or `npm run test`

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [x] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by ezehlivinus** [comment]
Codacy is complaining check the stuff and fix

**Review by OluwmayowaF — APPROVED** [review]
Noticed the updates to the app.js as you mentioned. Every other thing looks fine. 

The file named mix route can be a little confusing. I think naming the route with the action being performed - as you did for the others is easier for readability. 

At this point lets avoid this amount of large changes to the entire file structure as it would cause conflicts with everyone working asynchronously.

**Comment by vicradon** [comment]
Codacy issues 😁

**Review by vicradon — APPROVED** [review]
I'm not sure I'm following sha

**Comment by ezehlivinus** [comment]
I am approving this, though codacy issue need to be attended to.

**Review by ezehlivinus — APPROVED** [review]

**Pull request merged**
