### PR TITLE
Authentication setup

### LINKED ISSUE #10: [User Auth] Registration, Login and Password recovery route for Users ....
**As a User, I want to be able to create an account, sign in and recover my account**
- I should be able to create an account
- I should be able to sign in
- I should be able to recover my password by using a link

### PR DESCRIPTION
**Pull request by successtar**
## Description
This the Authentication part of the project in its simplest form.

Three endpoints are currently available for creating user account, Login and user account details.

The api documentation is available here https://documenter.getpostman.com/view/11412929/SzmjyaDv

## Point to note
- No email verification at present
- Account information and password updates are still in pipeline
- Forgot password option will also be put into consideration in future release
- The essence of this part is to get fully started with the backend development
- Contributions, suggestions, and corrections are highly welcome

## How Has This Been Tested?
Manual testing is currently used for the features, the unit testing for endpoints will be ready soonest.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by OluwmayowaF** [comment]
HI, I noticed that you. removed jest from the dev dependencies, why is this?
Can you write the required tests to test each endpoint?  @successtar

**Comment by successtar** [comment]
> 
> 
> HI, I noticed that you. removed jest from the dev dependencies, why is this?
> Can you write the required tests to test each endpoint? @successtar

I removed it so that it won't be part of dependencies that will be downloaded with npm install since I am not writing test yet.

But, if I will be witting test for this, I will prefer using Mocha and Chai.

**Comment by OluwmayowaF** [comment]
> > HI, I noticed that you. removed jest from the dev dependencies, why is this?
> > Can you write the required tests to test each endpoint? @successtar
> 
> I removed it so that it won't be part of dependencies that will be downloaded with npm install since I am not writing test yet.
> 
> But, if I will be witting test for this, I will prefer using Mocha and Chai.

Its important we write tests for every PR before it is merged, Is there a particular reason you don't want to use jest? I figured since the program is supported by Facebook using their products would be best. However, if it's based on a knowledge gap of not knowing jest I am open to the use of Mocha and Chai.

**Review by ezehlivinus — APPROVED** [review]

**Comment by successtar** [comment]
> 
> 
> > > HI, I noticed that you. removed jest from the dev dependencies, why is this?
> > > Can you write the required tests to test each endpoint? @successtar
> > 
> > 
> > I removed it so that it won't be part of dependencies that will be downloaded with npm install since I am not writing test yet.
> > But, if I will be witting test for this, I will prefer using Mocha and Chai.
> 
> Its important we write tests for every PR before it is merged, Is there a particular reason you don't want to use jest? I figured since the program is supported by Facebook using their products would be best. However, if it's based on a knowledge gap of not knowing jest I am open to the use of Mocha and Chai.

Yeah, I don't have issue with jest only that I have work more with api unit testing using Mocha and Chai than Jest and considering the time constraint I am trying to consider Mocha for fast delivery from my own end.

But for the Frontend, I may consider Jest as good fit since it is already integrated with react.

**Comment by successtar** [comment]
> 
> 
> > > > HI, I noticed that you. removed jest from the dev dependencies, why is this?
> > > > Can you write the required tests to test each endpoint? @successtar
> > > 
> > > 
> > > I removed it so that it won't be part of dependencies that will be downloaded with npm install since I am not writing test yet.
> > > But, if I will be witting test for this, I will prefer using Mocha and Chai.
> > 
> > 
> > Its important we write tests for every PR before it is merged, Is there a particular reason you don't want to use jest? I figured since the program is supported by Facebook using their products would be best. However, if it's based on a knowledge gap of not knowing jest I am open to the use of Mocha and Chai.
> 
> Yeah, I don't have issue with jest only that I have work more with api unit testing using Mocha and Chai than Jest and considering the time constraint I am trying to consider Mocha for fast delivery from my own end.
> 
> But for the Frontend, I may consider Jest as good fit since it is already integrated with react.

Any reasons for this pull request pending?

**Review by OluwmayowaF — APPROVED** [review]

**Comment by OluwmayowaF** [comment]
one more review is required...do a self review if no one attends to it

**Review by vicradon — APPROVED** [review]

**Pull request merged**
